### ISSUE TITLE
Link points to a non-existent website

### ISSUE THREAD

**Issue by IlievskiV** [UniversalDependencies/UD_Macedonian-MTB#2]
The link in the README file toward to the corpus called **Macedonian Language Digital Resources - MLDR** is pointing to a non-existent website as shown below:

![image](https://github.com/UniversalDependencies/UD_Macedonian-MTB/assets/4522582/56d15b22-db93-4494-9041-43c8f43df1be)

**Comment by dan-zeman** [comment]
Apparently this was already [fixed in the dev branch](https://github.com/UniversalDependencies/UD_Macedonian-MTB/commit/24376f8c06abaeee85e92bd14b7c781b0f4a7f78). It will be propagated to master with release 2.14 in May.

While the new README does not link to MLDR at all, [this link](http://drmj.manu.edu.mk/) currently works and leads to a resource with the same name (in Macedonian).
